= obs-docu adoc PoC

This is a proof-of-concept (PoC) showing how the existing OBS guides could be
converted to asciidoc.

== How to see the source code

https://github.com/smithfarm/smithfarm.github.io/tree/main/adoc

== How to see the asciidoc as rendered by GitHub

https://github.com/smithfarm/smithfarm.github.io/blob/main/adoc/obs-book/obs.adoc

== How to see the "final product" rendered to GitHub Pages

https://smithfarm.github.io

== How to test/build locally

The beauty of this solution is that running test builds locally is not strictly
necessary, because one can see the rendered asciidoc in GitHub.

That said, for any serious work on the OBS documentation, a local build setup
is essential. The easiest way to build locally is to run the same container
that the GitHub Pages deploy action uses:

[source,bash]
----
# from the top-level directory of the git repo
podman run -it --rm -v $PWD/:/docs/ \
    registry.opensuse.org/home/atgracey/cnbp/containers/builder:latest \
    bash -c 'cd /docs/adoc; daps -v -d DC-obs html'
----

This should produce output like:

[source,bash]
----
HTML book built with REMARKS=0, DRAFT=no and META=0:
/docs/adoc/build/obs/html/obs/
----

Since we bound the top-level directory of the git repo to /docs inside the
container, this just means the build put the rendered HTML into the local
directory `adoc/build/obs/html/obs/`, so that's the one to start serving
to our browser:

[source,bash]
----
cd adoc/build/obs/html/obs
python3 -m http.server
----

== How to set up a local dev environment without relying on a container

??
